### ISSUE TITLE
Gcode driver with TCP comms can't handle comms loss

### ISSUE THREAD

**Issue by ian-arkver** [openpnp/openpnp#1025]
# Problem Report
## Problem Description

Gcode driver with TCP comms can't handle comms loss.

When using the GcodeDriver with TCP communications, after initial connection if the connection is lost
the gcode driver throws a NullPointerException. If the connection is restored, the GcodeDriver cannot recover
and restore working operation. If the machine is stopped & restarted the attempt to restart fails with a Broken
Pipe error. A restart of openPnP is required.

## Steps to Reproduce

Configure a GcodeDriver instance with TCP comms. Connect to the remote gcode device. Break the comms,
eg. by disconnecting or power cycling the board. Attempt to reconnect.

## Expected Result

While this is surely a fatal error for any job in progress, openPnP itself should be able to recover without restarting the whole program. I would expect that it aborts the current job, moves to "disconnected" state and at least does setHomed(false).

## Actual Result

See above - NullPointerException followed by Broken Pipe errors. Log excerpt below...

```
2020-07-17 17:11:40.795 GcodeDriver DEBUG: sendCommand(G28 ; Home all axes, -1)...
2020-07-17 17:11:40.796 GcodeDriver TRACE: [tcp://127.0.0.1:1990] >> G28 ; Home all axes
2020-07-17 17:11:40.796 GcodeDriver TRACE: [tcp://127.0.0.1:1990] << ok
2020-07-17 17:11:40.796 GcodeDriver DEBUG: sendCommand(tcp://127.0.0.1:1990 G28 ; Home all axes, -1) => [ok]
2020-07-17 17:11:40.797 ReferenceNozzle DEBUG: N1.home()
2020-07-17 17:11:40.798 Scripting TRACE: Scripting.on Machine.AfterHoming
2020-07-17 17:11:40.798 ReferenceMachine DEBUG: setHomed(true)
2020-07-17 17:16:00.529 SystemLogger ERROR: Exception in thread "Thread-13" java.lang.NullPointerException
2020-07-17 17:16:00.529 SystemLogger ERROR: 	at org.openpnp.machine.reference.driver.GcodeDriver.run(GcodeDriver.java:1108)
2020-07-17 17:16:00.529 SystemLogger ERROR: 	at java.base/java.lang.Thread.run(Thread.java:834)
2020-07-17 17:16:34.363 ReferenceMachine DEBUG: setEnabled(false)
2020-07-17 17:16:34.365 ReferenceMachine DEBUG: setHomed(false)
2020-07-17 17:16:37.395 ReferenceMachine DEBUG: setEnabled(true)
2020-07-17 17:16:37.398 ReferenceMachine DEBUG: homing machine
2020-07-17 17:16:37.399 ReferenceMachine DEBUG: setHomed(false)
2020-07-17 17:16:37.400 ReferenceHead DEBUG: H1.home()
2020-07-17 17:16:37.401 GcodeDriver DEBUG: sendCommand(G28 ; Home all axes, -1)...
2020-07-17 17:16:37.401 GcodeDriver TRACE: [tcp://127.0.0.1:1990] >> G28 ; Home all axes
2020-07-17 17:16:37.401 MessageBoxes DEBUG: Enable Failure: Broken pipe (Write failed)
```

## Notes, Log Files, Screen Captures, Videos, etc. to Show the Issue

Log snippet above.
Whenever possible, please use the Menu -> Help -> Submit Diagnostics feature and include the URL here. Submit Diagnostics makes it easy to include log files, screen capture, debug images, configuration files, etc.

**Comment by ian-arkver** [comment]
The NPE is due to readline in the GcodeDriver's run loop returning null. This is passed to trim() without checking.

I added the following check...

```
                line = getCommunications().readLine();
                if (line == null) {
                    // Line read failed eg. due to socket closure
                    Logger.error("Failed to read tcp response");
                    return;
                }
                line = line.trim();
```

This prevents the NPE, but doesn't allow recovery. I'm not sure how to inform the rest of the system (from the Runnable thread) that a fatal comms error has happened and a disconnect/abort should happen.

One approach might be to push a "COMMSERROR" type message to the response queue, but in general it seems these responses are not actually checked.

Not sure how best to fix this.

**Comment by ian-arkver** [comment]
Note the above assumes TCP comms and doesn't apply to serial comms, so is hacky at best / more likely broken.
