### ISSUE TITLE
Exception when creating a new job

### ISSUE THREAD

**Issue by vonnieda** [openpnp/openpnp#114]
new job with job loaded causing exception?
	load demo job
	select BL
	select placement
	capture placement
	new job, no save

Exception in thread "AWT-EventQueue-0" java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.rangeCheck(ArrayList.java:653)
	at java.util.ArrayList.get(ArrayList.java:429)
	at java.util.Collections$UnmodifiableList.get(Collections.java:1309)
	at org.openpnp.gui.JobPanel.getSelectedBoardLocation(JobPanel.java:465)
	at org.openpnp.gui.JobPanel.getSelectedPlacement(JobPanel.java:470)
	at org.openpnp.gui.JobPanel$29.valueChanged(JobPanel.java:221)
	at javax.swing.DefaultListSelectionModel.fireValueChanged(DefaultListSelectionModel.java:184)
	at javax.swing.DefaultListSelectionModel.fireValueChanged(DefaultListSelectionModel.java:154)
	at javax.swing.DefaultListSelectionModel.setValueIsAdjusting(DefaultListSelectionModel.java:685)
	at javax.swing.JTable.clearSelectionAndLeadAnchor(JTable.java:2132)
	at javax.swing.JTable.sortedTableChanged(JTable.java:4147)
	at javax.swing.JTable.tableChanged(JTable.java:4395)
	at javax.swing.table.AbstractTableModel.fireTableChanged(AbstractTableModel.java:296)
	at javax.swing.table.AbstractTableModel.fireTableDataChanged(AbstractTableModel.java:198)
	at org.openpnp.gui.tablemodel.PlacementsTableModel.setBoard(PlacementsTableModel.java:78)
	at org.openpnp.gui.JobPanel$24.jobLoaded(JobPanel.java:1269)
	at org.openpnp.machine.reference.ReferenceJobProcessor.fireJobLoaded(ReferenceJobProcessor.java:791)
	at org.openpnp.machine.reference.ReferenceJobProcessor.load(ReferenceJobProcessor.java:113)
	at org.openpnp.gui.JobPanel$2.actionPerformed(JobPanel.java:732)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2346)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
	at javax.swing.AbstractButton.doClick(AbstractButton.java:376)
	at com.apple.laf.ScreenMenuItem.actionPerformed(ScreenMenuItem.java:125)
	at java.awt.MenuItem.processActionEvent(MenuItem.java:669)
	at java.awt.MenuItem.processEvent(MenuItem.java:628)
	at java.awt.MenuComponent.dispatchEventImpl(MenuComponent.java:351)
	at java.awt.MenuComponent.dispatchEvent(MenuComponent.java:339)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:761)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.awt.EventQueue$4.run(EventQueue.java:729)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at org.openpnp.gui.MainFrame$8.dispatchEvent(MainFrame.java:349)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

**Comment by vonnieda** [comment]
No longer able to reproduce. Likely fixed in refactoring of job loading in previous commit.
