### ISSUE TITLE
"Apply" in  Parts -> ReferenceBottomVision does not work/throws exception

### ISSUE THREAD

**Issue by doppelgrau** [openpnp/openpnp#1154]
# Problem Report
## Describe the Issue
After changing the "Rotation" in the "ReferenceBottomVision"-Settings of a part to "Full", bitting apply does not apply the setting, and on the console there is a exception thrown.

## Steps to Reproduce
1. Start OpenPnP (ideal from command line to see the exception)
2. Select a part in the Parts tab
3. Switch to the "ReferenceBottomVision"-Settings 
4. Switch the Rotation to "Full"
5. Hit apply

## Expected Result
The change will be applied, Apply button will deactivate after applying the change

## Actual Result
Change is not saved, Apply stays active, on the command line there is a exception like this one:

```
2021-03-14 22:06:42.439 SystemLogger ERROR: Exception in thread "AWT-EventQueue-0" java.lang.UnsupportedOperationException: Unwritable
2021-03-14 22:06:42.439 SystemLogger ERROR: 	at org.jdesktop.beansbinding.BeanProperty.setValue(BeanProperty.java:566)
2021-03-14 22:06:42.439 SystemLogger ERROR: 	at org.openpnp.gui.support.JBindings$WrappedBinding.save(JBindings.java:111)
2021-03-14 22:06:42.439 SystemLogger ERROR: 	at org.openpnp.gui.support.AbstractConfigurationWizard.saveToModel(AbstractConfigurationWizard.java:117)
2021-03-14 22:06:42.439 SystemLogger ERROR: 	at org.openpnp.gui.support.AbstractConfigurationWizard$1.actionPerformed(AbstractConfigurationWizard.java:176)
2021-03-14 22:06:42.439 SystemLogger ERROR: 	at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1967)
2021-03-14 22:06:42.439 SystemLogger ERROR: 	at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2308)
2021-03-14 22:06:42.440 SystemLogger ERROR: 	at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:405)
2021-03-14 22:06:42.440 SystemLogger ERROR: 	at java.desktop/javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:262)
2021-03-14 22:06:42.440 SystemLogger ERROR: 	at java.desktop/javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:279)
2021-03-14 22:06:42.440 SystemLogger ERROR: 	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6635)
2021-03-14 22:06:42.440 SystemLogger ERROR: 	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3342)
2021-03-14 22:06:42.440 SystemLogger ERROR: 	at java.desktop/java.awt.Component.processEvent(Component.java:6400)
2021-03-14 22:06:42.440 SystemLogger ERROR: 	at java.desktop/java.awt.Container.processEvent(Container.java:2263)
2021-03-14 22:06:42.440 SystemLogger ERROR: 	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5011)
2021-03-14 22:06:42.440 SystemLogger ERROR: 	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2321)
2021-03-14 22:06:42.440 SystemLogger ERROR: 	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4843)
2021-03-14 22:06:42.440 SystemLogger ERROR: 	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4918)
2021-03-14 22:06:42.440 SystemLogger ERROR: 	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4547)
2021-03-14 22:06:42.440 SystemLogger ERROR: 	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4488)
2021-03-14 22:06:42.440 SystemLogger ERROR: 	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2307)
2021-03-14 22:06:42.440 SystemLogger ERROR: 	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2772)
2021-03-14 22:06:42.440 SystemLogger ERROR: 	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4843)
2021-03-14 22:06:42.440 SystemLogger ERROR: 	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:772)
2021-03-14 22:06:42.440 SystemLogger ERROR: 	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
2021-03-14 22:06:42.440 SystemLogger ERROR: 	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
2021-03-14 22:06:42.440 SystemLogger ERROR: 	at java.base/java.security.AccessController.doPrivileged(Native Method)
2021-03-14 22:06:42.440 SystemLogger ERROR: 	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
2021-03-14 22:06:42.440 SystemLogger ERROR: 	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
2021-03-14 22:06:42.440 SystemLogger ERROR: 	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:745)
2021-03-14 22:06:42.440 SystemLogger ERROR: 	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:743)
2021-03-14 22:06:42.440 SystemLogger ERROR: 	at java.base/java.security.AccessController.doPrivileged(Native Method)
2021-03-14 22:06:42.440 SystemLogger ERROR: 	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
2021-03-14 22:06:42.440 SystemLogger ERROR: 	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
2021-03-14 22:06:42.440 SystemLogger ERROR: 	at org.openpnp.gui.MainFrame$20.dispatchEvent(MainFrame.java:462)
2021-03-14 22:06:42.440 SystemLogger ERROR: 	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
2021-03-14 22:06:42.440 SystemLogger ERROR: 	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
2021-03-14 22:06:42.440 SystemLogger ERROR: 	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
2021-03-14 22:06:42.440 SystemLogger ERROR: 	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
2021-03-14 22:06:42.440 SystemLogger ERROR: 	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
2021-03-14 22:06:42.440 SystemLogger ERROR: 	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

## Notes, Log Files, Screen Captures, Videos, etc. to Show the Issue
Probably introduced with the PR #1135 from @crashmatt 
SG-O had one branch without that change, no problem, after switching branches error appeared too.

**Comment by vonnieda** [comment]
Fixed, thanks for the report @doppelgrau!
