### ISSUE TITLE
error with connect to serial

### ISSUE THREAD

**Issue by whoim2** [openpnp/openpnp#1230]
Log:
```
2021-07-27 16:07:42.830 Main INFO: Bienvenue, Bienvenido, Willkommen, Hello, Namaskar, Welkom, Bonjour to OpenPnP version 2021-06-30_19-21-07.f42eedd.
2021-07-27 16:11:02.410 GcodeDriver$ReaderThread ERROR: Read error: java.io.IOException: Read error.
	at org.openpnp.machine.reference.driver.SerialPortCommunications.read(SerialPortCommunications.java:143)
	at org.openpnp.machine.reference.driver.ReferenceDriverCommunications.readUntil(ReferenceDriverCommunications.java:91)
	at org.openpnp.machine.reference.driver.ReferenceDriverCommunications.readLine(ReferenceDriverCommunications.java:71)
	at org.openpnp.machine.reference.driver.GcodeDriver$ReaderThread.run(GcodeDriver.java:1208)
2021-07-27 16:11:05.410 GcodeDriver ERROR: serial://COM10 failed to write command G21 ; Set millimeters mode: java.io.IOException: Write error.
	at org.openpnp.machine.reference.driver.SerialPortCommunications.writeBytes(SerialPortCommunications.java:154)
	at org.openpnp.machine.reference.driver.ReferenceDriverCommunications.writeLine(ReferenceDriverCommunications.java:75)
	at org.openpnp.machine.reference.driver.GcodeDriver.sendCommand(GcodeDriver.java:1005)
	at org.openpnp.machine.reference.driver.GcodeDriver.sendGcode(GcodeDriver.java:979)
	at org.openpnp.machine.reference.driver.GcodeDriver.sendGcode(GcodeDriver.java:961)
	at org.openpnp.machine.reference.driver.GcodeDriver.connect(GcodeDriver.java:379)
	at org.openpnp.machine.reference.driver.GcodeDriver.setEnabled(GcodeDriver.java:401)
	at org.openpnp.machine.reference.ReferenceMachine.setEnabled(ReferenceMachine.java:194)
	at org.openpnp.gui.MachineControlsPanel$2.lambda$actionPerformed$1(MachineControlsPanel.java:292)
	at java.lang.Thread.run(Unknown Source)
2021-07-27 16:11:05.410 GcodeDriver$ReaderThread ERROR: Read error: java.io.IOException: Read error.
	at org.openpnp.machine.reference.driver.SerialPortCommunications.read(SerialPortCommunications.java:143)
	at org.openpnp.machine.reference.driver.ReferenceDriverCommunications.readUntil(ReferenceDriverCommunications.java:91)
	at org.openpnp.machine.reference.driver.ReferenceDriverCommunications.readLine(ReferenceDriverCommunications.java:71)
	at org.openpnp.machine.reference.driver.GcodeDriver$ReaderThread.run(GcodeDriver.java:1208)
2021-07-27 16:11:05.410 ReferenceMachine INFO: setHomed(false)
```
use gcode driver, latest openpnp version and win7 x64 os..

**Comment by whoim2** [comment]
im connect with tcp, worked now.. )
