### ISSUE TITLE
Board load failed multiple points

### ISSUE THREAD

**Issue by chris1howell** [openpnp/openpnp#1392]
# Problem Report
## Describe the Issue
Eagle files will not load, including the Demo Board v1.brd file. Board load failed error multiple points.

## Steps to Reproduce
How can a developer reproduce the issue you are experiencing? Use a step by step format like this:
1. Start OpenPnP
2. Click the + Icon in Boards section of the Jobs tab
3. Select Existing
4. Navigate to the samples folder and select Demo Board v1.brd

## Expected Result
Board file should open

## Actual Result
Error
Board load failed 
multiple points

## Notes, Log Files, Screen Captures, Videos, etc. to Show the Issue
`2022-03-17 10:50:37.693 Main INFO: Bienvenue, Bienvenido, Willkommen, Hello, Namaskar, Welkom, Bonjour to OpenPnP version 2022-02-03_09-01-37.370b98b.
2022-03-17 10:50:37.694 Scripting TRACE: Scripting.on Startup
2022-03-17 10:50:38.982 AbstractBroadcastingCamera TRACE: Camera Top thread 25 started.
2022-03-17 10:50:40.243 AbstractBroadcastingCamera TRACE: Camera Bottom thread 27 started.
2022-03-17 10:51:17.190 SystemLogger ERROR: java.lang.NumberFormatException: multiple points

2022-03-17 10:51:17.191 SystemLogger ERROR: 	at sun.misc.FloatingDecimal.readJavaFormatString(Unknown Source)

2022-03-17 10:51:17.192 SystemLogger ERROR: 	at sun.misc.FloatingDecimal.parseDouble(Unknown Source)

2022-03-17 10:51:17.192 SystemLogger ERROR: 	at java.lang.Double.parseDouble(Unknown Source)

2022-03-17 10:51:17.192 SystemLogger ERROR: 	at java.lang.Double.valueOf(Unknown Source)

2022-03-17 10:51:17.192 SystemLogger ERROR: 	at org.simpleframework.xml.transform.DoubleTransform.read(DoubleTransform.java:55)

2022-03-17 10:51:17.193 SystemLogger ERROR: 	at org.simpleframework.xml.transform.DoubleTransform.read(DoubleTransform.java:42)

2022-03-17 10:51:17.193 SystemLogger ERROR: 	at org.simpleframework.xml.transform.Transformer.read(Transformer.java:106)

2022-03-17 10:51:17.193 SystemLogger ERROR: 	at org.simpleframework.xml.core.Support.read(Support.java:372)

2022-03-17 10:51:17.193 SystemLogger ERROR: 	at org.simpleframework.xml.core.PrimitiveFactory.getInstance(PrimitiveFactory.java:105)

2022-03-17 10:51:17.193 SystemLogger ERROR: 	at org.simpleframework.xml.core.Primitive.readTemplate(Primitive.java:231)

2022-03-17 10:51:17.193 SystemLogger ERROR: 	at org.simpleframework.xml.core.Primitive.read(Primitive.java:171)

2022-03-17 10:51:17.193 SystemLogger ERROR: 	at org.simpleframework.xml.core.Primitive.read(Primitive.java:126)

2022-03-17 10:51:17.193 SystemLogger ERROR: 	at org.simpleframework.xml.core.Composite.readVariable(Composite.java:623)

2022-03-17 10:51:17.193 SystemLogger ERROR: 	at org.simpleframework.xml.core.Composite.readInstance(Composite.java:573)

2022-03-17 10:51:17.194 SystemLogger ERROR: 	at org.simpleframework.xml.core.Composite.readVersion(Composite.java:377)

2022-03-17 10:51:17.194 SystemLogger ERROR: 	at org.simpleframework.xml.core.Composite.readVersion(Composite.java:352)

2022-03-17 10:51:17.194 SystemLogger ERROR: 	at org.simpleframework.xml.core.Composite.access$100(Composite.java:59)

2022-03-17 10:51:17.194 SystemLogger ERROR: 	at org.simpleframework.xml.core.Composite$Builder.read(Composite.java:1380)

2022-03-17 10:51:17.194 SystemLogger ERROR: 	at org.simpleframework.xml.core.Composite.read(Composite.java:201)

2022-03-17 10:51:17.194 SystemLogger ERROR: 	at org.simpleframework.xml.core.Composite.read(Composite.java:148)

2022-03-17 10:51:17.194 SystemLogger ERROR: 	at org.simpleframework.xml.core.Traverser.read(Traverser.java:92)

2022-03-17 10:51:17.194 SystemLogger ERROR: 	at org.simpleframework.xml.core.Persister.read(Persister.java:625)

2022-03-17 10:51:17.194 SystemLogger ERROR: 	at org.simpleframework.xml.core.Persister.read(Persister.java:606)

2022-03-17 10:51:17.194 SystemLogger ERROR: 	at org.simpleframework.xml.core.Persister.read(Persister.java:584)

2022-03-17 10:51:17.195 SystemLogger ERROR: 	at org.simpleframework.xml.core.Persister.read(Persister.java:543)

2022-03-17 10:51:17.195 SystemLogger ERROR: 	at org.simpleframework.xml.core.Persister.read(Persister.java:521)

2022-03-17 10:51:17.195 SystemLogger ERROR: 	at org.simpleframework.xml.core.Persister.read(Persister.java:426)

2022-03-17 10:51:17.195 SystemLogger ERROR: 	at org.openpnp.model.Configuration.loadBoard(Configuration.java:637)

2022-03-17 10:51:17.195 SystemLogger ERROR: 	at org.openpnp.model.Configuration.getBoard(Configuration.java:509)

2022-03-17 10:51:17.195 SystemLogger ERROR: 	at org.openpnp.gui.JobPanel$18.actionPerformed(JobPanel.java:1159)

2022-03-17 10:51:17.195 SystemLogger ERROR: 	at javax.swing.AbstractButton.fireActionPerformed(Unknown Source)

2022-03-17 10:51:17.195 SystemLogger ERROR: 	at javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source)

2022-03-17 10:51:17.195 SystemLogger ERROR: 	at javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source)

2022-03-17 10:51:17.195 SystemLogger ERROR: 	at javax.swing.DefaultButtonModel.setPressed(Unknown Source)

2022-03-17 10:51:17.196 SystemLogger ERROR: 	at javax.swing.AbstractButton.doClick(Unknown Source)

2022-03-17 10:51:17.196 SystemLogger ERROR: 	at javax.swing.plaf.basic.BasicMenuItemUI.doClick(Unknown Source)

2022-03-17 10:51:17.196 SystemLogger ERROR: 	at javax.swing.plaf.basic.BasicMenuItemUI$Handler.mouseReleased(Unknown Source)

2022-03-17 10:51:17.196 SystemLogger ERROR: 	at java.awt.AWTEventMulticaster.mouseReleased(Unknown Source)

2022-03-17 10:51:17.196 SystemLogger ERROR: 	at java.awt.Component.processMouseEvent(Unknown Source)

2022-03-17 10:51:17.196 SystemLogger ERROR: 	at javax.swing.JComponent.processMouseEvent(Unknown Source)

2022-03-17 10:51:17.196 SystemLogger ERROR: 	at java.awt.Component.processEvent(Unknown Source)

2022-03-17 10:51:17.196 SystemLogger ERROR: 	at java.awt.Container.processEvent(Unknown Source)

2022-03-17 10:51:17.196 SystemLogger ERROR: 	at java.awt.Component.dispatchEventImpl(Unknown Source)

2022-03-17 10:51:17.196 SystemLogger ERROR: 	at java.awt.Container.dispatchEventImpl(Unknown Source)

2022-03-17 10:51:17.196 SystemLogger ERROR: 	at java.awt.Component.dispatchEvent(Unknown Source)

2022-03-17 10:51:17.196 SystemLogger ERROR: 	at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)

2022-03-17 10:51:17.197 SystemLogger ERROR: 	at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)

2022-03-17 10:51:17.197 SystemLogger ERROR: 	at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)

2022-03-17 10:51:17.197 SystemLogger ERROR: 	at java.awt.Container.dispatchEventImpl(Unknown Source)

2022-03-17 10:51:17.197 SystemLogger ERROR: 	at java.awt.Window.dispatchEventImpl(Unknown Source)

2022-03-17 10:51:17.197 SystemLogger ERROR: 	at java.awt.Component.dispatchEvent(Unknown Source)

2022-03-17 10:51:17.197 SystemLogger ERROR: 	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)

2022-03-17 10:51:17.197 SystemLogger ERROR: 	at java.awt.EventQueue.access$500(Unknown Source)

2022-03-17 10:51:17.197 SystemLogger ERROR: 	at java.awt.EventQueue$3.run(Unknown Source)

2022-03-17 10:51:17.197 SystemLogger ERROR: 	at java.awt.EventQueue$3.run(Unknown Source)

2022-03-17 10:51:17.197 SystemLogger ERROR: 	at java.security.AccessController.doPrivileged(Native Method)

2022-03-17 10:51:17.197 SystemLogger ERROR: 	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)

2022-03-17 10:51:17.197 SystemLogger ERROR: 	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)

2022-03-17 10:51:17.197 SystemLogger ERROR: 	at java.awt.EventQueue$4.run(Unknown Source)

2022-03-17 10:51:17.198 SystemLogger ERROR: 	at java.awt.EventQueue$4.run(Unknown Source)

2022-03-17 10:51:17.198 SystemLogger ERROR: 	at java.security.AccessController.doPrivileged(Native Method)

2022-03-17 10:51:17.198 SystemLogger ERROR: 	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)

2022-03-17 10:51:17.198 SystemLogger ERROR: 	at java.awt.EventQueue.dispatchEvent(Unknown Source)

2022-03-17 10:51:17.198 SystemLogger ERROR: 	at org.openpnp.gui.MainFrame$2.dispatchEvent(MainFrame.java:480)

2022-03-17 10:51:17.198 SystemLogger ERROR: 	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)

2022-03-17 10:51:17.198 SystemLogger ERROR: 	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)

2022-03-17 10:51:17.198 SystemLogger ERROR: 	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)

2022-03-17 10:51:17.198 SystemLogger ERROR: 	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)

2022-03-17 10:51:17.198 SystemLogger ERROR: 	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)

2022-03-17 10:51:17.198 SystemLogger ERROR: 	at java.awt.EventDispatchThread.run(Unknown Source)

`

**Comment by markmaker** [comment]
The + button is for adding jobs that already have been converted to the native XML file format of OpenPnP.

For Eagle and others, use the **File / Import Board** commands instead. 

![image](https://user-images.githubusercontent.com/9963310/168464201-8b323e75-6dcd-49d6-88e6-94b12eee3b2f.png)

For further such help, please use the [discussion group](https://groups.google.com/group/openpnp).

_Mark
