### ISSUE TITLE
LibuvcCamera instantiation

### ISSUE THREAD

**Issue by lobsteroh** [openpnp/openpnp#236]
I am running into some issue while creating an instance of LibuvcCamera.

    import org.openpnp.machine.reference.camera.LibuvcCamera;
    public class LibuvcCamera_Example {
        public static void main(String[] args) {
            LibuvcCamera aCam = new LibuvcCamera();
        }
    }

The initialization fails with ...

`Exception in thread "main" java.lang.NoClassDefFoundError: org/openpnp/libuvc4j/UvcLibrary$uvc_frame_callback_t
	at openpnp_Example.LibuvcCamera_Example.main(LibuvcCamera_Example.java:7)
Caused by: java.lang.ClassNotFoundException: org.openpnp.libuvc4j.UvcLibrary$uvc_frame_callback_t
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 1 more
`

any suggestions? thanks,

**Comment by lobsteroh** [comment]
solved ... needed to include the libuvc4j lib separately, all good ...
