### ISSUE TITLE
Files from temp dir not deleted (at least in eclipse)

### ISSUE THREAD

**Issue by mgrl** [openpnp/openpnp#699]
I notice this error message in the eclipse's console every time I close openpnp. It doesn't matter whether I start openpnp from eclipse or standalone, the temporary copy remains so or so.

I'm on windows 7 64 bit. Seems not to hurt, but the system is full with temporary copies... maybe there is an easy fix?

Exception in thread "Thread-6" java.lang.RuntimeException: java.nio.file.AccessDeniedException: C:\Users\buero\AppData\Local\Temp\5119868789751822078\nu\pattern\opencv\windows\x86_64\opencv_java2411.dll
	at nu.pattern.OpenCV$TemporaryDirectory.delete(OpenCV.java:146)
	at nu.pattern.OpenCV$TemporaryDirectory$1.run(OpenCV.java:117)
Caused by: java.nio.file.AccessDeniedException: C:\Users\buero\AppData\Local\Temp\5119868789751822078\nu\pattern\opencv\windows\x86_64\opencv_java2411.dll
	at sun.nio.fs.WindowsException.translateToIOException(Unknown Source)
	at sun.nio.fs.WindowsException.rethrowAsIOException(Unknown Source)
	at sun.nio.fs.WindowsException.rethrowAsIOException(Unknown Source)
	at sun.nio.fs.WindowsFileSystemProvider.implDelete(Unknown Source)
	at sun.nio.fs.AbstractFileSystemProvider.deleteIfExists(Unknown Source)
	at java.nio.file.Files.deleteIfExists(Unknown Source)
	at nu.pattern.OpenCV$TemporaryDirectory$2.visitFile(OpenCV.java:141)
	at nu.pattern.OpenCV$TemporaryDirectory$2.visitFile(OpenCV.java:130)
	at java.nio.file.Files.walkFileTree(Unknown Source)
	at java.nio.file.Files.walkFileTree(Unknown Source)
	at nu.pattern.OpenCV$TemporaryDirectory.delete(OpenCV.java:130)
	... 1 more
[ERR ] PlatformContext creation failed (HRESULT = 00000001)!

**Comment by vonnieda** [comment]
This is a known issue in the OpenCV library. Please see https://github.com/openpnp/opencv/issues/5
