### ISSUE TITLE
Machine Setup Exception Errors

### ISSUE THREAD

**Issue by hukedev** [openpnp/openpnp#866]
# Problem Report
## Describe the Issue

Some gui errors occur.

## Steps to Reproduce

1. run clean openpnp develop (2019-06-29 18:54:44)
2. add some actuators, nozzle tips, a second nozzle 
3. quit and restart
4. click on machine setup items and on nozzle actuators
5. actuator entries wont get highlighted - errors occur (see log)

## Notes, Log Files, Screen Captures, Videos, etc. to Show the Issue

> 2019-06-30 16:39:50.368 SystemLogger ERROR: Exception in thread "AWT-EventQueue-0" java.lang.IndexOutOfBoundsException: Index: 1, Tab count: 1
> 
> 2019-06-30 16:39:50.369 SystemLogger ERROR: 	at javax.swing.JTabbedPane.checkIndex(Unknown Source)
> 
> 2019-06-30 16:39:50.370 SystemLogger ERROR: 	at javax.swing.JTabbedPane.setSelectedIndex(Unknown Source)
> 
> 2019-06-30 16:39:50.370 SystemLogger ERROR: 	at org.openpnp.gui.MachineSetupPanel$4.valueChanged(MachineSetupPanel.java:208)
> 
> 2019-06-30 16:39:50.371 SystemLogger ERROR: 	at javax.swing.tree.DefaultTreeSelectionModel.fireValueChanged(Unknown Source)
> 
> 2019-06-30 16:39:50.371 SystemLogger ERROR: 	at javax.swing.tree.DefaultTreeSelectionModel.notifyPathChange(Unknown Source)
> 
> 2019-06-30 16:39:50.371 SystemLogger ERROR: 	at javax.swing.tree.DefaultTreeSelectionModel.setSelectionPaths(Unknown Source)
> 
> 2019-06-30 16:39:50.371 SystemLogger ERROR: 	at javax.swing.tree.DefaultTreeSelectionModel.setSelectionPath(Unknown Source)
> 
> 2019-06-30 16:39:50.371 SystemLogger ERROR: 	at javax.swing.JTree.setSelectionPath(Unknown Source)
> 
> 2019-06-30 16:39:50.371 SystemLogger ERROR: 	at javax.swing.plaf.basic.BasicTreeUI.selectPathForEvent(Unknown Source)
> 
> 2019-06-30 16:39:50.371 SystemLogger ERROR: 	at javax.swing.plaf.basic.BasicTreeUI$Handler.handleSelection(Unknown Source)
> 
> 2019-06-30 16:39:50.372 SystemLogger ERROR: 	at javax.swing.plaf.basic.BasicTreeUI$Handler.mousePressed(Unknown Source)
> 
> 2019-06-30 16:39:50.372 SystemLogger ERROR: 	at java.awt.Component.processMouseEvent(Unknown Source)
> 
> 2019-06-30 16:39:50.372 SystemLogger ERROR: 	at javax.swing.JComponent.processMouseEvent(Unknown Source)
> 
> 2019-06-30 16:39:50.372 SystemLogger ERROR: 	at java.awt.Component.processEvent(Unknown Source)
> 
> 2019-06-30 16:39:50.372 SystemLogger ERROR: 	at java.awt.Container.processEvent(Unknown Source)
> 
> 2019-06-30 16:39:50.372 SystemLogger ERROR: 	at java.awt.Component.dispatchEventImpl(Unknown Source)
> 
> 2019-06-30 16:39:50.372 SystemLogger ERROR: 	at java.awt.Container.dispatchEventImpl(Unknown Source)
> 
> 2019-06-30 16:39:50.373 SystemLogger ERROR: 	at java.awt.Component.dispatchEvent(Unknown Source)
> 
> 2019-06-30 16:39:50.373 SystemLogger ERROR: 	at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
> 
> 2019-06-30 16:39:50.373 SystemLogger ERROR: 	at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
> 
> 2019-06-30 16:39:50.373 SystemLogger ERROR: 	at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
> 
> 2019-06-30 16:39:50.373 SystemLogger ERROR: 	at java.awt.Container.dispatchEventImpl(Unknown Source)
> 
> 2019-06-30 16:39:50.373 SystemLogger ERROR: 	at java.awt.Window.dispatchEventImpl(Unknown Source)
> 
> 2019-06-30 16:39:50.373 SystemLogger ERROR: 	at java.awt.Component.dispatchEvent(Unknown Source)
> 
> 2019-06-30 16:39:50.373 SystemLogger ERROR: 	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
> 
> 2019-06-30 16:39:50.374 SystemLogger ERROR: 	at java.awt.EventQueue.access$500(Unknown Source)
> 
> 2019-06-30 16:39:50.374 SystemLogger ERROR: 	at java.awt.EventQueue$3.run(Unknown Source)
> 
> 2019-06-30 16:39:50.374 SystemLogger ERROR: 	at java.awt.EventQueue$3.run(Unknown Source)
> 
> 2019-06-30 16:39:50.374 SystemLogger ERROR: 	at java.security.AccessController.doPrivileged(Native Method)
> 
> 2019-06-30 16:39:50.374 SystemLogger ERROR: 	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
> 
> 2019-06-30 16:39:50.374 SystemLogger ERROR: 	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
> 
> 2019-06-30 16:39:50.374 SystemLogger ERROR: 	at java.awt.EventQueue$4.run(Unknown Source)
> 
> 2019-06-30 16:39:50.374 SystemLogger ERROR: 	at java.awt.EventQueue$4.run(Unknown Source)
> 
> 2019-06-30 16:39:50.375 SystemLogger ERROR: 	at java.security.AccessController.doPrivileged(Native Method)
> 
> 2019-06-30 16:39:50.375 SystemLogger ERROR: 	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
> 
> 2019-06-30 16:39:50.375 SystemLogger ERROR: 	at java.awt.EventQueue.dispatchEvent(Unknown Source)
> 
> 2019-06-30 16:39:50.375 SystemLogger ERROR: 	at org.openpnp.gui.MainFrame$2.dispatchEvent(MainFrame.java:458)
> 
> 2019-06-30 16:39:50.375 SystemLogger ERROR: 	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
> 
> 2019-06-30 16:39:50.375 SystemLogger ERROR: 	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
> 
> 2019-06-30 16:39:50.375 SystemLogger ERROR: 	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
> 
> 2019-06-30 16:39:50.376 SystemLogger ERROR: 	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
> 
> 2019-06-30 16:39:50.376 SystemLogger ERROR: 	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
> 
> 2019-06-30 16:39:50.376 SystemLogger ERROR: 	at java.awt.EventDispatchThread.run(Unknown Source)

**Comment by hukedev** [comment]
I am not sure, but i think i found something. 

In `MachineSetupPanel.java` the last used tab of clicked node is stored in `lastSelectedTabIndex` that is not checked for available tab count before using it.

So i added a check to prevent index errors (line 206).

```
                            if (lastSelectedNode != null) {
                                if (lastSelectedNode.getClass().equals(node.obj.getClass())) {
                            		
                                    // tabbedPane.setSelectedIndex(lastSelectedTabIndex);

                                    if (!(lastSelectedTabIndex < -1 || 
                                          lastSelectedTabIndex > (tabbedPane.getTabCount() - 1))) {
                                	tabbedPane.setSelectedIndex(lastSelectedTabIndex);
                                    }
                                }
                            }
```

**Comment by hukedev** [comment]
Seems that OpenPnP 2.0 machine setup panel exception errors are gone now with above mods.
