### ISSUE TITLE
OSX Catalina version 10.15.3 works, but minor issues with ERROR messages on startup

### ISSUE THREAD

**Issue by brainstorm** [openpnp/openpnp#967]
# Problem Report

OpenPnP launches fine with `master` from today, but there are a few OSX integration rough edges to fix?

## Steps to Reproduce

```
$ git clone --depth 1 https://github.com/openpnp/openpnp.git
$ mvn -DskipTests install
$ ./openpnp.sh
```

## Expected Result

No errors.

## Actual Result

```
$ ./openpnp.sh
+ platform=unknown
++ uname
+ unamestr=Darwin
+ case "$unamestr" in
+ platform=mac
+++ dirname ./openpnp.sh
++ cd .
++ pwd -P
+ rootdir=/Users/romanvg/dev/openpnp
+ case "$platform" in
+ java -Xdock:name=OpenPnP -jar /Users/romanvg/dev/openpnp/target/openpnp-gui-0.0.1-alpha-SNAPSHOT.jar
javassist.NotFoundException: org.jdesktop.beansbinding.ELProperty
	at javassist.ClassPool.get(ClassPool.java:436)
	at org.openpnp.Main.monkeyPatchBeansBinding(Main.java:89)
	at org.openpnp.Main.main(Main.java:117)
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.openpnp.gui.support.OSXAdapter (file:/Users/romanvg/dev/openpnp/target/openpnp-gui-0.0.1-alpha-SNAPSHOT.jar) to constructor com.apple.eawt.Application()
WARNING: Please consider reporting this to the maintainers of org.openpnp.gui.support.OSXAdapter
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
2020-03-15 10:30:11.636 SystemLogger ERROR: This version of Mac OS X does not support the Apple EAWT.  ApplicationEvent handling has been disabled (java.lang.ClassNotFoundException: com.apple.eawt.ApplicationListener)
2020-03-15 10:30:11.639 SystemLogger ERROR: This version of Mac OS X does not support the Apple EAWT.  ApplicationEvent handling has been disabled (java.lang.ClassNotFoundException: com.apple.eawt.ApplicationListener)
2020-03-15 10:30:11.643 SystemLogger ERROR: OSXAdapter could not access the About Menu
2020-03-15 10:30:11.643 SystemLogger ERROR: java.lang.NoSuchMethodException: com.apple.eawt.Application.setEnabledAboutMenu(boolean)
2020-03-15 10:30:11.644 SystemLogger ERROR: 	at java.base/java.lang.Class.getDeclaredMethod(Class.java:2475)
2020-03-15 10:30:11.644 SystemLogger ERROR: 	at org.openpnp.gui.support.OSXAdapter.setAboutHandler(OSXAdapter.java:80)
2020-03-15 10:30:11.644 SystemLogger ERROR: 	at org.openpnp.gui.MainFrame.registerForMacOSXEvents(MainFrame.java:815)
2020-03-15 10:30:11.644 SystemLogger ERROR: 	at org.openpnp.gui.MainFrame.<init>(MainFrame.java:227)
2020-03-15 10:30:11.644 SystemLogger ERROR: 	at org.openpnp.Main$1.run(Main.java:152)
2020-03-15 10:30:11.645 SystemLogger ERROR: 	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
2020-03-15 10:30:11.645 SystemLogger ERROR: 	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
2020-03-15 10:30:11.645 SystemLogger ERROR: 	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
2020-03-15 10:30:11.645 SystemLogger ERROR: 	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
2020-03-15 10:30:11.645 SystemLogger ERROR: 	at java.base/java.security.AccessController.doPrivileged(Native Method)
2020-03-15 10:30:11.645 SystemLogger ERROR: 	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
2020-03-15 10:30:11.646 SystemLogger ERROR: 	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)
2020-03-15 10:30:11.646 SystemLogger ERROR: 	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
2020-03-15 10:30:11.646 SystemLogger ERROR: 	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
2020-03-15 10:30:11.646 SystemLogger ERROR: 	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
2020-03-15 10:30:11.646 SystemLogger ERROR: 	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
2020-03-15 10:30:11.647 SystemLogger ERROR: 	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
2020-03-15 10:30:11.647 SystemLogger ERROR: 	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
objc[82426]: Class PlatformAVCaptureDelegate is implemented in both /private/var/folders/wz/__dd9trs0kl4jb3rs83704y80000gn/T/jna-1377703278/jna10132287709418721017.tmp (0x15afbfbb0) and /private/var/folders/wz/__dd9trs0kl4jb3rs83704y80000gn/T/jna-1377703278/jna18099054187383761968.tmp (0x1665e0bb0). One of the two will be used. Which one is undefined.
OSX Unique ID is not exactly 18 characters - wrong format to extract location.
We might have trouble identifying the UVC control interface.
OSX Unique ID is not exactly 18 characters - wrong format to extract location.
We might have trouble identifying the UVC control interface.
2020-03-15 10:30:20.293 Main DEBUG: Bienvenue, Bienvenido, Willkommen, Hello, Namaskar, Welkom, Bonjour to OpenPnP version 2020-03-14_23-28-53.5389039.
2020-03-15 10:30:20.295 Scripting TRACE: Scripting.on Startup
2020-03-15 10:30:20.482 CameraView DEBUG: Failed to load camera specific reticle, checking default.
2020-03-15 10:30:20.485 CameraView DEBUG: No reticle preference found.
2020-03-15 10:30:20.516 CameraView DEBUG: Failed to load camera specific reticle, checking default.
2020-03-15 10:30:20.519 CameraView DEBUG: No reticle preference found.
2020-03-15 10:30:20.538 OpenPnpCaptureCamera WARNING: No camera found with ID USB 2.0 PC Cam (Unknown) 0x14111000514913d3 for camera Up
2020-03-15 10:30:20.539 CameraView DEBUG: Failed to load camera specific reticle, checking default.
2020-03-15 10:30:20.540 CameraView DEBUG: No reticle preference found.
2020-03-15 10:30:20.554 OpenPnpCaptureCamera WARNING: No camera found with ID USB 2.0 PC Cam #2 (Unknown) 0x14112000514913d3 for camera Down
2020-03-15 10:30:20.555 CameraView DEBUG: Failed to load camera specific reticle, checking default.
2020-03-15 10:30:20.555 CameraView DEBUG: No reticle preference found.
## Notes, Log Files, Screen Captures, Videos, etc. to Show the Issue
The more information you can provide about the issue the more likely it is that a developer will be able to respond.
```

**Comment by Jnesselr** [comment]
Seems to be related to this: https://docs.oracle.com/javase/9/migrate/toc.htm#JSMIG-GUID-C86F7403-7D7C-456F-8873-18C7F1BEDE2F
